branch-defaults:
  6-user-creation-and-login:
    environment: null
global:
  application_name: webshop
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: eu-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
